### ISSUE TITLE
Fill in readme with explanation of what this project is

### ISSUE THREAD

**Issue by cupOJoseph** [jschiarizzi/storj-ipfs-gateway#4]
Goal: give people who find this repo a good idea about what this project is, why it was created, and sources for more info on the tech used here

Include: 
- Simple ipfs explanation, its relation to storj/s3 and links to more IPFS reading
- Links to Storj docs for different parts of this that were used (storj CLI tool, Satellite use, configuring IPFS for storj, s3 config, etc.)
- Explanation of what an ipfs gateway is, why this one is super cool, and what you can do with this repo

**Comment by zyfrank** [comment]
Hi  @jschiarizzi
I think you should remove section "usage" of README. Because it is covered by section "Usage of Installer".
Even more it is outdated because current plugin implementation is a little different(It does not need to change ipfs related repo.)
